<?php
/**
 * Blog Factory — Import Pending Drafts
 *
 * Lists markdown drafts in blog_factory/queue/pending/ (generated by Claude Code's
 * /publish-blog command) and lets the admin import them into the posts table as
 * status='draft'. After import, files are moved to blog_factory/queue/imported/
 * for archival.
 *
 * Pipeline: /publish-blog → git push → Hostinger auto-pull → /admin/import-pending
 *           → click Import → row in posts table → review in /admin/posts/ → publish.
 */

require_once __DIR__ . '/_layout.php';
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/csrf.php';
require_once __DIR__ . '/../includes/slugify.php';
require_once __DIR__ . '/../includes/post_helpers.php';
require_once __DIR__ . '/../includes/webp.php';

$user = require_auth();

$ROOT         = realpath(__DIR__ . '/..');
$PENDING_DIR  = $ROOT . '/blog_factory/queue/pending';
$IMPORTED_DIR = $ROOT . '/blog_factory/queue/imported';
$IMAGES_SRC   = $PENDING_DIR . '/images';

// Handle POST actions (import / delete) before rendering.
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_verify();
    $action = $_POST['action'] ?? '';
    $slug   = preg_replace('/[^a-z0-9-]/i', '', $_POST['slug'] ?? '');

    if ($action === 'import' && $slug !== '') {
        $result = import_pending_post($slug, $PENDING_DIR, $IMPORTED_DIR, $IMAGES_SRC, $ROOT, (int)$user['id']);
        flash_set($result['ok'] ? 'success' : 'error', $result['message']);
        $redirect = $result['ok'] && !empty($result['post_id'])
            ? '/admin/posts/edit.php?id=' . (int)$result['post_id']
            : '/admin/import-pending.php';
        header('Location: ' . $redirect, true, 302);
        exit;
    }

    if ($action === 'delete' && $slug !== '') {
        $deleted = delete_pending_post($slug, $PENDING_DIR, $IMAGES_SRC);
        flash_set($deleted ? 'success' : 'error',
            $deleted ? "Deleted pending draft: $slug" : "Could not delete: $slug");
        header('Location: /admin/import-pending.php', true, 302);
        exit;
    }
}

// Render list of pending drafts.
$pending = list_pending_drafts($PENDING_DIR);

layout_start('Import pending drafts');
echo flash_render();
?>
<section class="panel">
  <div class="panel-head">
    <h2>Pending drafts from <code>/publish-blog</code> (<?= count($pending) ?>)</h2>
    <a class="btn-secondary" href="/admin/posts/">View all posts</a>
  </div>

  <?php if (!$pending): ?>
    <p class="muted">
      No pending drafts. Run <code>/publish-blog "your topic"</code> in Claude Code on your local machine,
      then check this page again after the GitHub push and Hostinger auto-pull (~30 seconds).
    </p>
  <?php else: ?>
    <table class="data-table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Slug</th>
          <th>Words</th>
          <th>Generated</th>
          <th>Image</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($pending as $p): ?>
          <tr>
            <td>
              <strong><?= htmlspecialchars($p['title']) ?></strong>
              <?php if (!empty($p['service_tag'])): ?>
                <br><span class="muted"><?= htmlspecialchars($p['service_tag']) ?></span>
              <?php endif ?>
            </td>
            <td><code><?= htmlspecialchars($p['slug']) ?></code></td>
            <td><?= isset($p['word_count']) ? (int)$p['word_count'] : '?' ?></td>
            <td><?= htmlspecialchars($p['generated_at'] ?? '') ?></td>
            <td>
              <?php if ($p['has_image']): ?>
                <span style="color:#16a34a;">✓ <?= number_format($p['image_size_kb']) ?> KB</span>
              <?php else: ?>
                <span style="color:#dc2626;">missing</span>
              <?php endif ?>
            </td>
            <td>
              <form method="post" style="display:inline;">
                <?= csrf_field() ?>
                <input type="hidden" name="action" value="import">
                <input type="hidden" name="slug" value="<?= htmlspecialchars($p['slug']) ?>">
                <button type="submit" class="btn-primary">Import</button>
              </form>
              <form method="post" style="display:inline;"
                    onsubmit="return confirm('Delete this pending draft permanently? The markdown file and image will be removed.');">
                <?= csrf_field() ?>
                <input type="hidden" name="action" value="delete">
                <input type="hidden" name="slug" value="<?= htmlspecialchars($p['slug']) ?>">
                <button type="submit" class="btn-danger">Delete</button>
              </form>
            </td>
          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
    <p class="muted" style="margin-top:1rem;">
      Each Import inserts the post as <code>status=draft</code>. Open it in
      <a href="/admin/posts/">Posts</a>, review the content, then change status to Published to go live.
    </p>
  <?php endif ?>
</section>
<?php layout_end(); ?>
<?php

// ---------- helpers ----------

function list_pending_drafts(string $dir): array {
    if (!is_dir($dir)) return [];
    $files = glob($dir . '/*.md') ?: [];
    sort($files);
    $rows = [];
    foreach ($files as $file) {
        $parsed = parse_pending_file($file);
        if (!$parsed) continue;
        $slug = $parsed['frontmatter']['slug'] ?? basename($file, '.md');
        $img_path = $dir . '/images/' . $slug . '.jpg';
        $img_path_alt = $dir . '/images/' . $slug . '.webp';
        $img_size = is_file($img_path) ? filesize($img_path) : (is_file($img_path_alt) ? filesize($img_path_alt) : 0);
        $rows[] = [
            'slug'           => $slug,
            'title'          => $parsed['frontmatter']['title'] ?? $slug,
            'service_tag'    => $parsed['frontmatter']['service_tag'] ?? '',
            'word_count'     => $parsed['frontmatter']['word_count'] ?? null,
            'generated_at'   => $parsed['frontmatter']['generated_at'] ?? '',
            'has_image'      => $img_size > 0,
            'image_size_kb'  => (int)round($img_size / 1024),
        ];
    }
    return $rows;
}

function parse_pending_file(string $path): ?array {
    $raw = @file_get_contents($path);
    if ($raw === false) return null;
    if (!preg_match('/^---\s*\n(.*?)\n---\s*\n(.*)$/s', $raw, $m)) return null;
    $fm = parse_simple_yaml($m[1]);
    return ['frontmatter' => $fm, 'body' => $m[2]];
}

// Minimal YAML parser — handles key: value and key: "value" lines.
// Does NOT support nested objects, arrays, multiline values, anchors. That's
// fine because the /publish-blog command emits a flat frontmatter shape.
function parse_simple_yaml(string $yaml): array {
    $out = [];
    foreach (preg_split("/\r?\n/", $yaml) as $line) {
        $line = rtrim($line);
        if ($line === '' || $line[0] === '#') continue;
        if (!preg_match('/^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*)$/', $line, $m)) continue;
        $key = $m[1];
        $val = trim($m[2]);
        // Strip surrounding quotes if present.
        if (strlen($val) >= 2) {
            $first = $val[0]; $last = $val[strlen($val) - 1];
            if (($first === '"' && $last === '"') || ($first === "'" && $last === "'")) {
                $val = substr($val, 1, -1);
                if ($first === '"') $val = str_replace('\\"', '"', $val);
            }
        }
        // Cast numerics.
        if (preg_match('/^-?\d+$/', $val))       $val = (int)$val;
        elseif (preg_match('/^-?\d+\.\d+$/', $val)) $val = (float)$val;
        $out[$key] = $val;
    }
    return $out;
}

function import_pending_post(
    string $slug, string $pending_dir, string $imported_dir,
    string $images_src, string $repo_root, int $author_id
): array {
    $md_file = $pending_dir . '/' . $slug . '.md';
    if (!is_file($md_file)) {
        return ['ok' => false, 'message' => "No markdown file for slug: $slug"];
    }
    $parsed = parse_pending_file($md_file);
    if (!$parsed) {
        return ['ok' => false, 'message' => "Could not parse frontmatter in $slug.md"];
    }
    $fm   = $parsed['frontmatter'];
    $body = $parsed['body'];

    // Move and convert image into /uploads/YYYY/MM/.
    $img_url = move_pending_image($slug, $images_src, $repo_root);

    // Build the post payload. Image fields override anything in frontmatter so
    // we always end up with a real /uploads/ URL (not the queue path).
    $data = [
        'title'            => trim((string)($fm['title'] ?? '')),
        'excerpt'          => trim((string)($fm['excerpt'] ?? '')),
        'content'          => post_sanitize_html($body),
        'featured_image'   => $img_url ?: '',
        'meta_title'       => trim((string)($fm['meta_title'] ?? '')),
        'meta_description' => trim((string)($fm['meta_description'] ?? '')),
        'og_image'         => $img_url ?: '',
        'canonical_url'    => trim((string)($fm['canonical_url'] ?? '')),
        'status'           => 'draft',
        'publish_at'       => null,
    ];

    $errors = post_validate($data);
    if ($errors) {
        return ['ok' => false, 'message' => 'Validation: ' . implode(' · ', $errors)];
    }

    // Slug uniqueness — if there's a collision (existing post with same slug),
    // slug_unique() appends -2, -3, etc.
    $final_slug = slug_unique(slugify((string)($fm['slug'] ?? $slug)));

    $post_id = db_exec(
        'INSERT INTO posts
           (slug, title, excerpt, content, featured_image,
            meta_title, meta_description, og_image, canonical_url,
            status, publish_at, author_id)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
        'sssssssssssi',
        [
            $final_slug, $data['title'], $data['excerpt'], $data['content'], $data['featured_image'],
            $data['meta_title'], $data['meta_description'], $data['og_image'], $data['canonical_url'],
            $data['status'], $data['publish_at'], $author_id
        ]
    );

    post_regenerate_sitemap();

    // Archive the markdown file.
    if (!is_dir($imported_dir)) @mkdir($imported_dir, 0755, true);
    $archive_path = $imported_dir . '/' . $slug . '-' . date('Ymd-His') . '.md';
    @rename($md_file, $archive_path);

    return [
        'ok'      => true,
        'message' => "Imported as draft #$post_id (slug: $final_slug). Open in Posts to review and publish.",
        'post_id' => $post_id,
    ];
}

/**
 * Move the pending image into /uploads/YYYY/MM/, converting to WebP if needed.
 * Returns the public URL path, or empty string on failure.
 */
function move_pending_image(string $slug, string $images_src, string $repo_root): string {
    $candidates = [
        $images_src . '/' . $slug . '.webp',
        $images_src . '/' . $slug . '.jpg',
        $images_src . '/' . $slug . '.jpeg',
        $images_src . '/' . $slug . '.png',
    ];
    $src = null;
    foreach ($candidates as $c) { if (is_file($c)) { $src = $c; break; } }
    if (!$src) return '';

    $year  = date('Y');
    $month = date('m');
    $rel_dir = "/uploads/$year/$month";
    $abs_dir = $repo_root . $rel_dir;
    if (!is_dir($abs_dir)) @mkdir($abs_dir, 0755, true);

    $base   = $slug . '-' . substr(bin2hex(random_bytes(3)), 0, 6);
    $webp_dst = $abs_dir . '/' . $base . '.webp';

    $ok = false;
    if (pathinfo($src, PATHINFO_EXTENSION) === 'webp') {
        $ok = @copy($src, $webp_dst);
    } else {
        $ok = image_to_webp($src, $webp_dst, 85);
    }

    if (!$ok) {
        // WebP conversion failed (GD missing?) — fall back to copying the original.
        $orig_dst = $abs_dir . '/' . $base . '.' . pathinfo($src, PATHINFO_EXTENSION);
        if (@copy($src, $orig_dst)) {
            @unlink($src);
            return "$rel_dir/" . basename($orig_dst);
        }
        return '';
    }

    @unlink($src);
    return "$rel_dir/" . basename($webp_dst);
}

function delete_pending_post(string $slug, string $pending_dir, string $images_src): bool {
    $md = $pending_dir . '/' . $slug . '.md';
    $ok = is_file($md) ? @unlink($md) : false;
    foreach (['webp', 'jpg', 'jpeg', 'png'] as $ext) {
        $img = $images_src . '/' . $slug . '.' . $ext;
        if (is_file($img)) @unlink($img);
    }
    return $ok;
}
